#spring.application.name=cafe-management
#server.port=${PORT:8080}
#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.show-sql=false
spring.application.name=cafe-management
server.port=${PORT:8080}
# T? ??ng chuy?n ??i: Trên mây dùng bi?n DB_URL, ? máy nhà dùng localhost:5433
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/quanlycafe}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:123456}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false