spring.application.name=cafe-management
spring.datasource.url=jdbc:postgresql://localhost:5433/quanlycafe
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update